# Project identification
sonar.projectKey=Sentinel-JuiceShop
sonar.projectName=Sentinels SAST
sonar.projectVersion=1.0

# Source code configuration
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/coverage/**, **/test-results/**

# Language configuration
sonar.javascript.lcov.reportPaths=build/reports/coverage/lcov.info
sonar.javascript.xunit.reportPaths=test-results/TEST-*.xml

# Quality gate configuration
sonar.qualitygate.wait=true
